// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: protos/hotel-service/hotel.proto

package hotelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomNumber    int32   `protobuf:"varint,1,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	RoomType      string  `protobuf:"bytes,2,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	PricePerNight float32 `protobuf:"fixed32,3,opt,name=price_per_night,json=pricePerNight,proto3" json:"price_per_night,omitempty"`
	Availability  bool    `protobuf:"varint,4,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_service_hotel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_service_hotel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_protos_hotel_service_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetRoomNumber() int32 {
	if x != nil {
		return x.RoomNumber
	}
	return 0
}

func (x *Room) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *Room) GetPricePerNight() float32 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *Room) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

type Hotel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelId  string `protobuf:"bytes,1,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Rating   int32  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Address  string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_service_hotel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_service_hotel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_protos_hotel_service_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *Hotel) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *Hotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hotel) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Hotel) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Hotel) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListOfHotelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListOfHotelRequest) Reset() {
	*x = ListOfHotelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_service_hotel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfHotelRequest) ProtoMessage() {}

func (x *ListOfHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_service_hotel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfHotelRequest.ProtoReflect.Descriptor instead.
func (*ListOfHotelRequest) Descriptor() ([]byte, []int) {
	return file_protos_hotel_service_hotel_proto_rawDescGZIP(), []int{2}
}

type ListOfHotelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Hotel `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListOfHotelResponse) Reset() {
	*x = ListOfHotelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_service_hotel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfHotelResponse) ProtoMessage() {}

func (x *ListOfHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_service_hotel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfHotelResponse.ProtoReflect.Descriptor instead.
func (*ListOfHotelResponse) Descriptor() ([]byte, []int) {
	return file_protos_hotel_service_hotel_proto_rawDescGZIP(), []int{3}
}

func (x *ListOfHotelResponse) GetList() []*Hotel {
	if x != nil {
		return x.List
	}
	return nil
}

type GetDetailsOfHotelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelId string `protobuf:"bytes,1,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
}

func (x *GetDetailsOfHotelRequest) Reset() {
	*x = GetDetailsOfHotelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_service_hotel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDetailsOfHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsOfHotelRequest) ProtoMessage() {}

func (x *GetDetailsOfHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_service_hotel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsOfHotelRequest.ProtoReflect.Descriptor instead.
func (*GetDetailsOfHotelRequest) Descriptor() ([]byte, []int) {
	return file_protos_hotel_service_hotel_proto_rawDescGZIP(), []int{4}
}

func (x *GetDetailsOfHotelRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

type GetDetailsOfHotelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelId  string  `protobuf:"bytes,1,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location string  `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Rating   int32   `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Address  string  `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Rooms    []*Room `protobuf:"bytes,6,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *GetDetailsOfHotelResponse) Reset() {
	*x = GetDetailsOfHotelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_service_hotel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDetailsOfHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsOfHotelResponse) ProtoMessage() {}

func (x *GetDetailsOfHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_service_hotel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsOfHotelResponse.ProtoReflect.Descriptor instead.
func (*GetDetailsOfHotelResponse) Descriptor() ([]byte, []int) {
	return file_protos_hotel_service_hotel_proto_rawDescGZIP(), []int{5}
}

func (x *GetDetailsOfHotelResponse) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *GetDetailsOfHotelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDetailsOfHotelResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetDetailsOfHotelResponse) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GetDetailsOfHotelResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetDetailsOfHotelResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type GetAvailabilityRoomsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelId string `protobuf:"bytes,1,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
}

func (x *GetAvailabilityRoomsRequest) Reset() {
	*x = GetAvailabilityRoomsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_service_hotel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailabilityRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityRoomsRequest) ProtoMessage() {}

func (x *GetAvailabilityRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_service_hotel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailabilityRoomsRequest) Descriptor() ([]byte, []int) {
	return file_protos_hotel_service_hotel_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvailabilityRoomsRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

type AvailabilityRooms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType       string `protobuf:"bytes,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	AvailableRooms int32  `protobuf:"varint,2,opt,name=available_rooms,json=availableRooms,proto3" json:"available_rooms,omitempty"`
}

func (x *AvailabilityRooms) Reset() {
	*x = AvailabilityRooms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_service_hotel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailabilityRooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityRooms) ProtoMessage() {}

func (x *AvailabilityRooms) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_service_hotel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityRooms.ProtoReflect.Descriptor instead.
func (*AvailabilityRooms) Descriptor() ([]byte, []int) {
	return file_protos_hotel_service_hotel_proto_rawDescGZIP(), []int{7}
}

func (x *AvailabilityRooms) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *AvailabilityRooms) GetAvailableRooms() int32 {
	if x != nil {
		return x.AvailableRooms
	}
	return 0
}

type GetAvailabilityRoomsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*AvailabilityRooms `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetAvailabilityRoomsResponse) Reset() {
	*x = GetAvailabilityRoomsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_service_hotel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailabilityRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityRoomsResponse) ProtoMessage() {}

func (x *GetAvailabilityRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_service_hotel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailabilityRoomsResponse) Descriptor() ([]byte, []int) {
	return file_protos_hotel_service_hotel_proto_rawDescGZIP(), []int{8}
}

func (x *GetAvailabilityRoomsResponse) GetList() []*AvailabilityRooms {
	if x != nil {
		return x.List
	}
	return nil
}

var File_protos_hotel_service_hotel_proto protoreflect.FileDescriptor

var file_protos_hotel_service_hotel_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x84, 0x01, 0x0a, 0x05, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12,
	0x19, 0x0a, 0x08, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x14, 0x0a, 0x12,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x31, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x4f, 0x66, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x64, 0x22, 0xb5, 0x01, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x48, 0x6f, 0x74,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f,
	0x74, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f,
	0x74, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72,
	0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x38, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x59,
	0x0a, 0x11, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x6f,
	0x6f, 0x6d, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x27, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x46, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x6f, 0x6f, 0x6d,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x32, 0xe9, 0x01, 0x0a, 0x0c, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x12, 0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x48,
	0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x12, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66,
	0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x48, 0x6f, 0x74, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x73,
	0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a,
	0x12, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x74, 0x65,
	0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_hotel_service_hotel_proto_rawDescOnce sync.Once
	file_protos_hotel_service_hotel_proto_rawDescData = file_protos_hotel_service_hotel_proto_rawDesc
)

func file_protos_hotel_service_hotel_proto_rawDescGZIP() []byte {
	file_protos_hotel_service_hotel_proto_rawDescOnce.Do(func() {
		file_protos_hotel_service_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_hotel_service_hotel_proto_rawDescData)
	})
	return file_protos_hotel_service_hotel_proto_rawDescData
}

var file_protos_hotel_service_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_hotel_service_hotel_proto_goTypes = []any{
	(*Room)(nil),                         // 0: Room
	(*Hotel)(nil),                        // 1: Hotel
	(*ListOfHotelRequest)(nil),           // 2: ListOfHotelRequest
	(*ListOfHotelResponse)(nil),          // 3: ListOfHotelResponse
	(*GetDetailsOfHotelRequest)(nil),     // 4: GetDetailsOfHotelRequest
	(*GetDetailsOfHotelResponse)(nil),    // 5: GetDetailsOfHotelResponse
	(*GetAvailabilityRoomsRequest)(nil),  // 6: GetAvailabilityRoomsRequest
	(*AvailabilityRooms)(nil),            // 7: AvailabilityRooms
	(*GetAvailabilityRoomsResponse)(nil), // 8: GetAvailabilityRoomsResponse
}
var file_protos_hotel_service_hotel_proto_depIdxs = []int32{
	1, // 0: ListOfHotelResponse.list:type_name -> Hotel
	0, // 1: GetDetailsOfHotelResponse.rooms:type_name -> Room
	7, // 2: GetAvailabilityRoomsResponse.list:type_name -> AvailabilityRooms
	2, // 3: HotelService.ListOfHotel:input_type -> ListOfHotelRequest
	4, // 4: HotelService.GetDetailsOfHotel:input_type -> GetDetailsOfHotelRequest
	6, // 5: HotelService.GetAvailabilityRooms:input_type -> GetAvailabilityRoomsRequest
	3, // 6: HotelService.ListOfHotel:output_type -> ListOfHotelResponse
	5, // 7: HotelService.GetDetailsOfHotel:output_type -> GetDetailsOfHotelResponse
	8, // 8: HotelService.GetAvailabilityRooms:output_type -> GetAvailabilityRoomsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_hotel_service_hotel_proto_init() }
func file_protos_hotel_service_hotel_proto_init() {
	if File_protos_hotel_service_hotel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_hotel_service_hotel_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_service_hotel_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Hotel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_service_hotel_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListOfHotelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_service_hotel_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListOfHotelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_service_hotel_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetDetailsOfHotelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_service_hotel_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetDetailsOfHotelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_service_hotel_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAvailabilityRoomsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_service_hotel_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AvailabilityRooms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_service_hotel_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetAvailabilityRoomsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_hotel_service_hotel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_hotel_service_hotel_proto_goTypes,
		DependencyIndexes: file_protos_hotel_service_hotel_proto_depIdxs,
		MessageInfos:      file_protos_hotel_service_hotel_proto_msgTypes,
	}.Build()
	File_protos_hotel_service_hotel_proto = out.File
	file_protos_hotel_service_hotel_proto_rawDesc = nil
	file_protos_hotel_service_hotel_proto_goTypes = nil
	file_protos_hotel_service_hotel_proto_depIdxs = nil
}
